### ISSUE TITLE
[API 요청] 사서 로테이션 관련 기능 개발에 필요한 API를 요청합니다.

### ISSUE THREAD

**Issue by jhj9109** [Together42/backend#171]
## description
> 사서 로테이션 관련 기능 개발에 필요한 API를 요청합니다.

## todo
- [ ] `GET` `"/api/rotation/attend"` -> `Attend[]`
    - 유저 본인의 사서 로테이션 신청기록 전체를 리턴합니다.
    - 당장 필요한것은 유저 본인의 이번달 사서 로테이션 신청 여부에 대한 조회입니다.
    - 혹시나 모를 범용성을 위해 요청자 본인의 전체 기록 리턴으로 요청합니다.

**Comment by sideseal** [comment]
넵, 유저 본인의 사서 로테이션 신청 기록에 대한 API 제작 수행하겠습니다!!
